baseURL = "https://metalcar.github.io/portfolio/"
languageCode = "de-de"
title = "Carmine D'Amico | Full-Stack Developer"
defaultContentLanguage = "de"
enableRobotsTXT = true

[params]
  description = "Portfolio von Carmine D'Amico, Full-Stack Developer"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
